# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# https://beta.ruff.rs/docs
name: ruff
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user ruff
    - run: ruff --format=github --extend-exclude=backend/apps/users/migrations
                --ignore=F401 --line-length=114 --target-version=py37 .
